[package]
name = "error"
authors.workspace = true
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
regex.workspace = true
reqwest.workspace = true
