name: ОБНОВЛЕНИЕ СТАТИСТИКИ WAKATIME

on:
  workflow_dispatch:
  schedule:
    # Этот workflow будет запускаться КАЖДЫЙ ЧАС
    - cron: "0 */1 * * *"

jobs:
  update-readme:
    name: urdekcah
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: all_time
          SHOW_TOTAL: true
          IGNORED_LANGUAGES: YAML JSON TOML MARKDOWN GIT HTML CSS
          COMMIT_MESSAGE: Обновлен файл readme с новыми метриками графика wakatime
